- name: Create temp directory for installer script
  file:
    path: "{{ tmp_dir }}"
    state: directory

- name: Get nix installer script
  get_url:
    url: https://nixos.org/nix/install
    dest: "{{ tmp_dir }}/install"

- name: Execute install script
  command: "bash {{ tmp_dir }}/install"
