# Path to your oh-my-zsh installation.
export ZSH=/Users/sgillis/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="my-minimal"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH="/Users/sgillis/bin:/Users/sgillis/git/config/bin:/Users/sgillis/.nix-profile/bin:/Users/sgillis/.nix-profile/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/sgillis/.nix-profile/bin:/Users/sgillis/.nix-profile/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

export DOCKER_HOST="tcp://10.2.0.10:4243"

alias dnsdock='docker run -d --name dnsdock -p 172.18.42.2:53:53/udp tonistiigi/dnsdock -docker="tcp://172.18.42.2:4243"'
alias skydns='docker run -d -p 10.2.0.10:53:53/udp --name skydns crosbymichael/skydns -nameserver 8.8.8.8:53 -domain docker'
alias skydock='docker run -d --name skydock crosbymichael/skydock -ttl 30 -environment dev -s "tcp://10.2.0.10:4243" -domain docker -name skydns'
alias route-docker='sudo route -n add -net 172.17.0.0 10.2.0.10'
alias nvim="~/git/docker-neovim/run_nvim.sh"
alias docker-pylint="~/git/docker-neovim/run_pylint.sh"
alias em="emacsclient -t"
if [ -e /Users/sgillis/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/sgillis/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

unsetopt incappendhistory

eval $(docker-machine env default)

export PATH=/Users/sgillis/.local/bin:$PATH
source /Users/sgillis/git/git-subrepo/.rc